name: CI Build

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker images
      run: docker compose build

    - name: Test Docker run
      run: docker compose up -d && sleep 5 && curl http://localhost:8084 && docker compose down