name: CI Build

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker images
      id: docker_build
      run: docker compose build
      continue-on-error: true

    - name: Test Docker run
      id: docker_test
      run: docker compose up -d && sleep 5 && curl http://localhost:8084 && docker compose down
      if: steps.docker_build.outcome == 'success'

    - name: Send email on build failure
      if: steps.docker_build.outcome == 'failure'
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{ secrets.MAIL_USERNAME }}
        password: ${{ secrets.MAIL_PASSWORD }}
        subject: Docker Build Failure - ${{ github.repository }}
        to: ${{ secrets.MAIL_RECIPIENT }}
        from: GitHub Actions <noreply@github.com>
        body: |
          The Docker build failed for repository: ${{ github.repository }}
          Branch: ${{ github.ref_name }}
          Commit: ${{ github.sha }}
          Check the build logs for details: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

    - name: Send email on build success
      if: steps.docker_build.outcome == 'success'
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{ secrets.MAIL_USERNAME }}
        password: ${{ secrets.MAIL_PASSWORD }}
        subject: Docker Build Success - ${{ github.repository }}
        to: ${{ secrets.MAIL_RECIPIENT }}
        from: GitHub Actions <noreply@github.com>
        body: |
          The Docker build succeeded for repository: ${{ github.repository }}
          Branch: ${{ github.ref_name }}
          Commit: ${{ github.sha }}
          View the build details: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}